global using Shipping.Entities;
global using Shipping.Data;
global using FastEndpoints;
global using Shipping.Enums;
global using Shipping.Shared;
global using Shipping.Shared.Authentication;
global using Mapster;
global using Shipping.Contracts;    
global using Shipping.Extensions;
global using Order = Shipping.Entities.Order;
global using IMapper = MapsterMapper.IMapper;